### ISSUE TITLE
Trouble extending from templates

### ISSUE THREAD

**Issue by x80486** [mxmul/snowpack-plugin-nunjucks#1]
I integrated `snowpack-plugin-nunjucks` `0.0.3` in a brand new "core Web" project. My `snowpack.config.js` is quite simple:

```javascript
/** @type { import("snowpack").SnowpackUserConfig } */
export default {
  devOptions: {
    open: "none",
  },
  env: {
    // ...
  },
  mount: {
    src: {
      url: "/",
    },
  },
  optimize: {
    bundle: true,
    minify: true,
    target: "es2018",
  },
  plugins: [
    "@snowpack/plugin-webpack",
    "snowpack-plugin-nunjucks",
  ],
};
```

Within `src` I've started to put together all the pieces, so I have an `index.njk`:

```html
{% set title = "Home" %}

// Notice that files must be referenced from the project's root
{% extends "src/_layout.njk" %}

...
```

After I run Snowpack's build, I still see the Nunjucks templates (prefixed by `_file_name.[ext]`, for instance, `_layout.njk`) being "generated" inside `build`.

I believe those files should be excluded, right? Only those `.njk` or `.html` files within `src` that aren't prefixed with `_` should be processed and finally copied over into `build`.

**Comment by mxmul** [comment]
I'd recommend keeping your layouts/partials outside of the mounted directory, and doing something like this in `index.njk`:

```
{% set title = "Home" %}

{% extends "layouts/_layout.njk" %}
...
```

But yeah, I agree we should probably not be processing these files at all (I think returning `null` in `load()` would do the trick?). PRs welcome if you want to try!

**Comment by x80486** [comment]
OK, so you are saying that basically I could create a `layout` sub-directory (at the same level than `src`, for my case) and place there the actual layouts 🤔

I can certainly do that, and it wouldn't be a weird solution at all, but I'm really hooked up with the `_private_thing_syntax.njk`, so let me see if I understand this good enough to give it a shot.

**Comment by x80486** [comment]
Looking at the EJS plugin, I think [returning right away](https://github.com/xuxinhang/snowpack-plugin-ejs/blob/08f03eb4dfcd656844c21889a669943a103a1eb9/index.js#L61) if the file starts with `_` should do it as well.
